# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b4ed39a3c6454c2d062dfbbd8101d9483187966781fbfd3b27dcbfa4eee4169bea4d876a85ed7fca7e4788bfaf4301fad872349eed2e0f2d4a65ed31b0ac4b3

test:
  secret_key_base: a8a0e42fdd5610836b5ecd14cb2686154b7eab649b53491bac05836fa81c3e9518b31852c3f1cd58d8cb97ce952b147ff085acd04b49c84d941fad34f77537ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
